version: '3'
# 最終的には、名前付きボリュームは使うが土台を作り上げてから有効にする。
# volumes:
#   eng_word_data:

services:

  db:
    build: ./eng_word/postgresql
    container_name: eng_word_db
    ports:
      - '4532:5432'
    # volumes:
    #   - 'eng_word_data:/var/lib/postgresql/data'
    environment:
      - POSTGRES_PASSWORD=eng_word
      - POSTGRES_DB=eng_word
      - POSTGRES_USER=eng_word
      - '~/Shellscripts:/Shellscripts'
    tty: true
    stdin_open: true

  python:
    build: ./eng_word/python
    container_name: eng_word_app
    ports:
      - '8001:8000'
    volumes:
      - './eng_word/python:/code'
    depends_on:
      - db
    tty: true
